import numpy as np
from scipy.special import gamma
import pickle
import pdb
import numpy as np
import matplotlib.pyplot as plt
import pdb
import copy
import pandas as pd
from os.path import exists
font = {"size": 16}

feature_data = np.asarray([["id", "patient identification number", " ", "unused", "no", "irrelevant"],
    ["ccf", "social security number", " ", "unused", "no", "irrelevant"],
    ["age", "age in years", "continuous", "basic", "yes", " "],
    ["sex", "sex (1 = male; 0 = female)", "binary", "basic", "yes", " "],
    ["painloc", "chest pain location (1 = substernal; 0 = otherwise)", "binary", "basic", "no", " "],
    ["painexer", "(1 = provoked by exertion; 0 = otherwise)", "binary", "basic", "no", " "],
    ["relrest", "(1 = relieved after rest; 0 = otherwise)", "binary", "basic", "no", " "],
    ["pncaden", "pncaden (sum of 5, 6, and 7)...unclear", "continuos", "unused", "no", "unclear"],
    ["cp", "chest pain type", "categorical", "basic", "yes", " "],
    ["trestbps", "resting blood pressure", "continuous", "technical", "yes", " "],
    ["htn", "hypertension", "binary", "technical", "no", " "],
    ["chol", "serum cholestoral", "continuous", "technical", "yes", " "],
    ["smoke", "is or is not a smoker", "binary", "basic", "no", " "],
    ["cigs", "cigarettes per day", "continuous", "basic", "no", " "],
    ["years", "number of years as a smoker", "continuous", "basic", "no", " "],
    ["fbs", "fasting blood sugar", "continuous", "technical", "yes", " "],
    ["dm", "history of diabetes", "binary", "basic", "no", " "],
    ["famhist", "family history of coronary artery disease", "binary", "basic", "no", " "],
    ["restecg", "resting electrocardiographic results", "categorical", "technical", "no", " "],
    ["ekgmo", "month of exercise ECG reading", "continuos", "unused", "no", "irrelevant"],
    ["ekgday", "day of exercise ECG reading", "continuos", "unused", "no", "irrelevant"],
    ["ekgyr", "year of exercise ECG reading", "continuos", "unused", "no", "irrelevant"],
    ["dig", "digitalis used furing exercise", "binary", "technical", "no", " "],
    ["prop", "Beta blocker used during exercise ECG", "binary", "technical", "no", " "],
    ["nitr", "nitrates used during exercise ECG", "binary", "technical", "no", " "],
    ["pro", "calcium channel blocker used during exercise ECG", "binary", "technical", "no", " "],
    ["diuretic", "diuretic used used during exercise ECG", "binary", "technical", "no", " "],
    ["proto", "exercise protocol", "categorical", "technical", "no", " "],
    ["thaldur", "duration of exercise test", "continuous", "technical", "no", " "],
    ["thaltime", "time when ST measure depression was noted", "continuous", "technical", "no", " "],
    ["met", "mets achieved", "continuous", "technical", "no", " "],
    ["thalach", "maximum heart rate achieved", "continuous", "technical", "yes", " "],
    ["thalrest", "resting heart rate", "continuous", "technical", "no", " "],
    ["tpeakbps", "peak exercise blood pressure (systolic)", "continuous", "technical", "no", " "],
    ["tpeakbpd", "peak exercise blood pressure (diastolic)", "continuous", "technical", "no", " "],
    ["dummy", " ", " ", "unused", "no", " "],
    ["trestbpd", "resting blood pressure", "continuous", "technical", "no", " "],
    ["exang", "exang: exercise induced angina", "binary", "technical", "yes", " "],
    ["xhypo", "hypoxia?", "binary", "technical", "no", " "],
    ["oldpeak", "ST depression induced by exercise relative to rest", "continuous", "technical", "yes", " "],
    ["slope", "slope of the peak exercise ST segment", "categorical", "technical", "yes", " "],
    ["rldv5", "height at rest", "continuous", "technical", "no", " "],
    ["rldv5e", "height at peak exercise", "continuous", "technical", "no", " "],
    ["ca", "number of major vessels (0-3) colored by flourosopy", "continuous", "technical", "yes", " "],
    ["restckm", "irrelevant", " ", "unused", "no", "missing data"],
    ["exerckm", "irrelevant", " ", "unused", "no", "missing data"],
    ["restef", "rest raidonuclid ejection fraction", " ", "unused", "no", "missing data"],
    ["restwm", "rest wall motion abnormality", "categorical","unused", "no", "missing data"],
    ["exeref", "exeref: exercise radinalid ejection fraction", " ", "unused", "no", "missing data"],
    ["exerwm", "exerwm: exercise wall (sp?) motion ", " ", "unused", "no", "missing data"],
    ["thal", "unclear", "categorical", "technical", "yes", " "],
    ["thalsev", "not used", " ", "unused", "no", "missing data"],
    ["thalpul", "not used", " ", "unused", "no", "missing data"],
    ["earlobe", "not used", " ", "unused", "no", "missing data"],
    ["cmo", "month of cardiac catheterization", "continuos", "unused", "no", "irrelevant"],
    ["cday", "day of cardiac catheterization", "continuos", "unused", "no", "irrelevant"],
    ["cyr", "year of cardiac catheterization", "continuos", "unused", "no", "irrelevant"],
    ["num", "diagnosis of heart disease", "binary", "technical", "yes", " "],
    ["lmt", "narrowing of left main trunk artery", "binary", "technical", "no", " "],
    ["ladprox", "narrowing of left anterior descending artery (proximal)", "binary", "technical", "no", " "],
    ["laddist", "narrowing of left anterior descending artery (distal)", "binary", "technical", "no", " "],
    ["diag", "narrowing of left anterior descending artery (diagonal branch)", "binary", "technical", "no", " "],
    ["cxmain", "narrowing of main circumflex artery", "binary", "technical", "no", " "],
    ["ramus", "narrowing of ramus coronary artery", "binary", "technical", "no", " "],
    ["om1", "narrowing of obtuse marginal coronary artery 1", "binary", "technical", "no", " "],
    ["om2", "narrowing of obtuse marginal coronary artery 2", "binary", "technical", "no", " "],
    ["rcaprox", "narrowing of right coronary artery (proximal)", "binary", "technical", "no", " "],
    ["rcadist", "narrowing of right coronary artery (distal)", "binary", "technical", "no", " "],
    ["lvx1", "narrowing of left circumflex artery 1", "binary", "unused", "no", "labeled unused"],
    ["lvx2", "narrowing of left circumflex artery 4", "binary", "unused", "no", "labeled unused"],
    ["lvx3", "narrowing of left circumflex artery 3", "binary", "unused", "no", "labeled unused"],
    ["lvx4", "narrowing of left circumflex artery 4", "binary", "unused", "no", "labeled unused"],
    ["lvf", "left ventricular failure?", "binary", "unused", "no", "labeled unused"],
    ["cathef", "not used", " ", "unused", "no", "missing data"],
    ["junk",  "not used", " ", "unused", "no", "missing data"]
])

np.savetxt("feature_table.csv", feature_data, delimiter=' & ', fmt = '%s', newline=' \\\\\n')
